# https://github.com/actions/deploy-pages#usage
name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Zëvendësojmë Node.js me Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Instalimi i paketave me Bun
      - run: bun install
      
      # Gjenerimi i build-it me Bunx (ekuivalenti i npx)
      - run: bunx nuxt build --preset github_pages
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.output/public
          
  # Deployment job (Mbetet i pandryshuar)
  deploy:
    needs: build
    permissions:
      pages: write      
      id-token: write   
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
